# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1961491d8000f238a3bbed077fe7a2a322eb8a37193b6763854dfb952ccf308805c4c1c83011c1091f5ce1a08eb4b5bee14c4e45024ea47e5283f9c31c5a53f9

test:
  secret_key_base: 4899e7e0c3b1de8a476a48a64c4a5868d6b9c7b8b5b4fa5a11e3f219570ac60539ae14e70ecc8f22965c7c7c2e639534db3832150b2e5cbbbd21f43d007b18fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
